CREATE TABLE "E_LIBRARIAN"
(
    "ID" INTEGER PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "MOBILE" INTEGER NOT NULL
);
