CREATE TABLE "E_BOOK"
(
    "CALLNO" VARCHAR(255) PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "AUTHOR" VARCHAR(255) NOT NULL,
    "PUBLISHER" VARCHAR(255) NOT NULL,
    "QUANTITY" INTEGER,
    "ISSUED" INTEGER
);
