CREATE TABLE "E_ISSUEBOOK"
(
    "CALLNO" VARCHAR(255) not null primary key,
    "STUDENTID" VARCHAR(255) NOT NULL,
    "STUDENTNAME" VARCHAR(255) NOT NULL,
    "STUDENTMOBILE" INTEGER,
    "ISSUEDDATE" DATE,
    "RETURNSTATUS" VARCHAR(255) NOT NULL
);
