CREATE TABLE  "E_BOOK" 
   (	"CALLNO" VARCHAR(50), 
	"NAME" VARCHAR(100), 
	"AUTHOR" VARCHAR(50), 
	"PUBLISHER" VARCHAR2(50), 
	"QUANTITY" INT, 
	"ISSUED" INT, 
	 CONSTRAINT "E_BOOK_PK" PRIMARY KEY ("CALLNO")
   )

CREATE TABLE  "E_LIBRARIAN" 
   (	"ID" INT, 
	"NAME" VARCHAR(50), 
	"PASSWORD" VARCHAR(50), 
	"EMAIL" VARCHAR(50), 
	"MOBILE" INT, 
	 CONSTRAINT "E_LIBRARIAN_PK" PRIMARY KEY ("ID")
   )


CREATE TABLE  "E_ISSUEBOOK" 
   (	"CALLNO" VARCHAR(50) NOT NULL ENABLE, 
	"STUDENTID" VARCHAR(50) NOT NULL ENABLE, 
	"STUDENTNAME" VARCHAR(50), 
	"STUDENTMOBILE" INT, 
	"ISSUEDDATE" DATE,
	"RETURNSTATUS" VARCHAR(50)
   )
/


